config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("stores/", include("stores.urls", namespace="stores")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from stores import views as store_views

app_name = "core"

urlpatterns = [path("", store_views.Homeview.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("update-profile", views.UpdateProfileView.as_view(), name="update"),
    path("update-password", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    &copy : BPLUS
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute max-auto left-0 right-0 top-0 flex justify-center">
        {% for message in messages %}
        <li class="message font-medium bg-gray-700 rounded-lg text-full z-10 py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-bold h-full">
    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{{user.get_absolute_url}}">Profile</a>
    </li>
    <li class="nav_link">
        <a href='{% url "users:logout" %}'>Logout</a>
    </li>
    {% else %}
    <li class="nav_link">
        <a href='{% url "users:login" %}'>Login</a>
    </li>
    <li class="nav_link">
        <a href='{% url "users:signup" %}'>Sign Up</a>
    </li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href='{% url "users:kakao-login" %}' class="btn mb-2 border bg-yellow-500  font-bold text-gray-100">
        <i class="fas fa-comment mr-2"></i>Continue with Kakao
    </a>
</div>
<div class="flex items-center w-full my-4">
    <div class='h-px w-full bg-gray-500'></div>
    <span class='text-gray-700 font-medium mx-4'>or</span>
    <div class='h-px w-full bg-gray-500'></div>
</div>