config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("stores/", include("stores.urls", namespace="stores")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from stores import views as store_views

app_name = "core"

urlpatterns = [path("", store_views.Homeview.as_view(), name="home")]

stores/urls.py
from django.urls import path
from . import views as store_views

app_name = "stores"


""" urlpatterns of FBV"""
# urlpatterns = [path("<int:pk>", store_views.store_detail, name="detail")]

""" urlpatterns of CBV """
urlpatterns = [
    path("<int:pk>", store_views.StoreDetail.as_view(), name="detail"),
    path("search/", store_views.search, name="search"),
]

templates/mixins/auth_form.html
<form method="POST" class='w-full'>
    
    {% csrf_token %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            {{error}}
        {% endfor %}
    {% endif %}

    {% for field in form %}
    <div class="input">
        {{field}}
        {% if field.errors %}
            {% for error in field.errors %}
                <span class="text-red-700 font-medium text-sm">{{error}}</span>
            {% endfor %}
        {% endif %}    
    </div>
    {% endfor %}

    <button class='btn'>{{cta}}</button>
</form> 

templates/mixins/store_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'stores:detail' store.pk%}">
        <div class="w-full h-64 mb-8 bg-cover bg-center background-image: url({store.first_photo})">
        </div>
        <div class="flex justify-end">
            <span class="'text-sm flex items-center">
                <i class="fas fa-star text-red-300 text-xs mr-2"></i>{{store.total_avg}}
            </span>
        </div>
        <span class="w-11/12  block truncate">
            <a class="text-black" href="{% url "stores:detail" store.pk %}">
                {{store.name}}
            </a>
        </span>
    </a>

</div>

templates/mixins/user_avatar.html
<div class='h-20 w-20 bg-gray-700 rounded-full text-white flex justify-center items-center'>
    <span class='text-3xl'>{{user.email|first}}</span> 
</div>