config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("stores/", include("stores.urls", namespace="stores")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from stores import views as store_views

app_name = "core"

urlpatterns = [path("", store_views.Homeview.as_view(), name="home")]

stores/urls.py
from django.urls import path
from . import views as store_views

app_name = "stores"


""" urlpatterns of FBV"""
# urlpatterns = [path("<int:pk>", store_views.store_detail, name="detail")]

""" urlpatterns of CBV """
urlpatterns = [
    path("<int:pk>", store_views.StoreDetail.as_view(), name="detail"),
    path("search/", store_views.search, name="search"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <title>{% block page_title%}{% endblock page_title%}</title>
</head>
<body class="text-gray-700 mt-24 font-light">
    {% include 'partials/messages.html' %}
    <header class="container max-w-full flex items-center justify-between px-6 h-20 border-b border-gray-500 fixed inset-0 bg-white">
        <div class="flex w-1/3">
            {% block search-bar %}
            <a  href="{% url "core:home" %}" class="mr-6">
                <img class='w-8' src="{% static 'img/BPLUS_symbol.png' %}">
            </a>
            <form method='get' action='{% url "stores:search" %}' class="w-9/12">
                <input class='search-box border px-5 py-2 rounded-sm text-sm font-medium placeholder-gray-600 w-full shadow-md hover:shadow-lg focus:outline-none' name='city' placeholder='Search' />
            </form>
            {% endblock search-bar %}
        </div>
        {% include 'partials/nav.html' %}
    </header>
    {% block content %}{% endblock content %}
    {% include 'partials/footer.html' %}
</body>
</html>