config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("stores/", include("stores.urls", namespace="stores")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from stores import views as store_views

app_name = "core"

urlpatterns = [path("", store_views.Homeview.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("update-profile", views.UpdateProfileView.as_view(), name="update"),
    path("update-password", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string


class User(AbstractUser):

    """Custom User Model"""

    USERNAME_FILED = "email"
    # REQUIRED_FIELDS = []

    LOGIN_EMAIL = "email"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = ((LOGIN_EMAIL, "Email"), (LOGIN_KAKAO, "Kakao"))

    name = models.CharField("이름", max_length=100)
    email = models.EmailField("email address", unique=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=16, default="", blank=True)

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:16]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=True,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist"))


class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("email", "name")
        widgets = {
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
            "name": forms.TextInput(attrs={"placeholder": "이름"}),
        }

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView, DetailView, UpdateView
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from . import forms, models


class LoginView(View):
    def get(self, request):
        form = forms.LoginForm()
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome back {user.email}")
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})


def log_out(request):
    logout(request)
    messages.info(request, "See you later")
    return redirect(reverse("core:home"))


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.save()
    except models.User.DoesNotExist:
        pass
    return redirect(reverse("core:home"))


def kakao_login(request):
    REST_API_KEY = os.environ.get("KAKAO_KEY")
    REDIRECT_URI = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    client_id = os.environ.get("KAKAO_KEY")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    try:
        code = request.GET.get("code")
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get authorization code.")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={
                "Authorization": f"Bearer {access_token}",
            },
        )
        profile_json = profile_request.json()
        email = profile_json.get("kakao_account").get("email", None)
        if email is None:
            raise KakaoException("Please also give me your email.")
        try:
            user = models.User.objects.get(email=email)
            if user.login_method != models.User.LOGIN_KAKAO:
                raise KakaoException("Please login with: {{user.login_method}}")
        except models.User.DoesNotExist:
            user = models.User.objects.create(
                username=email,
                email=email,
                login_method=models.User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
        login(request, user)
        messages.success(requests, f"Welcome back {user.email}")
        return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(requests, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = ("name",)

    def get_object(self, queryset=None):
        return self.request.user


class UpdatePasswordView(PasswordChangeView):
    template_name = "users/update-password.html"

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Login
{% endblock page_title%}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<div class='container xl: w-1/4 lg:w-5/12 md:w:1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400'>
    {% include 'partials/social_login.html' %}

    {% include 'mixins/auth_form.html' with form=form cta="Log in" %}

    <div class="'mt-5">
        <span class="mr-2">Don't have an account?</span>
        <a href="{% url 'users:signup' %}" class="text-teal-500 font-bold">Sign up</a>
    </div>
</div>

{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title%}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<div class='container xl: w-1/4 lg:w-5/12 md:w:1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400'>
    {% include 'partials/social_login.html' %}

    {% include 'mixins/auth_form.html' with form=form cta="Sign Up" %}

    <div class="'mt-5">
        <span class="mr-2">Have an account?</span>
        <a href="{% url 'users:login' %}" class="text-teal-500 font-bold">Sign In</a>
    </div>
</div>

{% endblock content %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title%}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<div class='container xl: w-1/4 lg:w-5/12 md:w:1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400'>

    {% include 'mixins/auth_form.html' with form=form cta="Update Password" %}
</div>

{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Profile
{% endblock page_title%}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<div class='container xl: w-1/4 lg:w-5/12 md:w:1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400'>

    {% include 'mixins/auth_form.html' with form=form cta="Update Profile" %}

    {% if object.login_method == "email" %}
        <div class="'mt-5">
            <a href="{% url 'users:password' %}" class="text-teal-500 font-bold">Change Password</a>
        </div>

    {% endif %}
</div>

{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    Profile
{% endblock page_title%}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<div class="h-4/5">
    <div class='container xl: w-1/4 lg:w-5/12 md:w:1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400'>
        {% include 'mixins/user_avatar.html' with user=user_obj%}
            <span class='font-medium text-2xl mt-2'>{{user_obj.email}}</span>
        {% if user == user_obj %}
            <a href="{% url 'users:update' %}" class='btn-link'>Edit Profile</a>
        {% endif %}
    </div>
    {% if user_obj.stores.count > 0%}
    <div class='container mx-auto pb-10flex flex-col items-center'>
        <h3 class='mb-20 text-2xl'>My Store</h3>
        <div class="flex flex-wrap -mx-10 mb-10">
            {{user_obj.name}}
            {% for store in user_obj.stores.all %}
                {% include 'mixins/store_card.html' with store=store %}
            {% endfor %}
        </div>
    </div>
    {% endif %}
<div>


{% endblock content %}